services:
  db:
    image: postgres:latest
    platform: linux/amd64
    container_name: wiki-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - wiki-network

  backend:
    build: ./backend
    platform: linux/amd64
    container_name: wiki-api
    env_file: .env
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - wiki-network

  frontend:
    build: ./frontend
    platform: linux/amd64
    container_name: wiki-ui
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - wiki-network

networks:
  wiki-network:
    driver: bridge
