apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: wiki-backend
    newName: ghcr.io/kwyczlinski/wiki-backend
    newTag: latest
  - name: wiki-frontend
    newName: ghcr.io/kwyczlinski/wiki-frontend
    newTag: latest
