apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - authentik.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy-db.yaml
  - networkpolicy-redis.yaml

configMapGenerator:
  - name: postgres-init-scripts
    namespace: wiki-app
    files:
      - db/00_init_auth_db.sql
      - db/01_init.sql
      - db/02_comments.sql
      - db/03_functions.sql

secretGenerator:
  - name: wiki-secrets
    namespace: wiki-app
    envs:
      - .env