name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read
  security-events: write # required for Snyk to save reports to security tab

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Layer 1: Python at backend ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Backend Dependencies
        run: |
          cd backend
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Snyk to check Python vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=backend/requirements.txt --package-manager=pip --sarif-file-output=snyk-python.sarif

      # --- Layer 2: Node.js at frontend ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Run Snyk to check Node.js vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=frontend/package.json --sarif-file-output=snyk-node.sarif

      # --- Layer 3: IaC at docker compose ---
      - name: Run Snyk to check Docker Compose / Infrastructure as Code
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: docker-compose.yml --sarif-file-output=snyk-iac.sarif

      # ---  Sending raportów to Security tab on GitHub ---
      - name: Upload Snyk Python results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-python.sarif
          category: snyk-python

      - name: Upload Snyk Node results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-node.sarif
          category: snyk-node

      - name: Upload Snyk IaC results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-iac.sarif
          category: snyk-iac
