name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read
  security-events: write # Snyk can write raports

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/actions/checkout@v4

      # --- Layer 1: python at backend ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Backend Dependencies
        run: |
          cd backend
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Snyk to check Python vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true # raport and continue testing
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=backend/requirements.txt --package-manager=pip

      # ---Layer 2 node.js at frontend ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # update if vite updates to use newer

      - name: Run Snyk to check Node.js vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=frontend/package.json

      # --- Layer 3: IAAC at docker compose ---
      - name: Run Snyk to check Docker Compose / Infrastructure as Code
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: docker-compose.yml
